### ISSUE TITLE
Device type is always phone

### ISSUE THREAD

**Issue by eterry1388** [net-angel/netangel-protection-android#2]
Login is always using "phone" as the device type:

``` java
args.put(DEVICE_TYPE, "phone");
```

Should detect if on a tablet vs phone vs kindle, etc.

Here are the current types supported on the Rails backend:

``` ruby
enum device_type: [:other, :phone, :tablet, :desktop, :laptop, :chromebook, :router, :inline]
```

**Comment by klinker24** [comment]
Do you want to add other types to this, or a device name column in the database? I can send up anything. It is easy to tell a tablet from a phone, and I can even get the device information (manufacturer/model) if that would be more descriptive for the user. For example, we could have 

```
device_type = phone
device_name = "Google, Pixel XL"
```

Or, would you rather just stick to `tablet` vs `phone` on the backend?

**Comment by klinker24** [comment]
Actually, looks like the make/model of the phone is already being sent up, so that should be an issue. Not sure why I didn't notice that the first time. 

#17 will close out this issue and explains how resources work in android for tablets vs phones.

**Comment by eterry1388** [comment]
I have tested this and it works with both a tablet and a phone.
