### ISSUE TITLE
Ensure VPN is on the NetAngel VPN

### ISSUE THREAD

**Issue by eterry1388** [net-angel/netangel-protection-android#21]
Need to make sure the VPN that is on is our VPN and not another one that could potentially be used to bypass the filter.  Without any changes on the VPN side, I can think of 2 ways to see if you are on our VPN.

1. You could ping 172.18.0.1.  If it is reachable, you are on the NetAngel VPN.  Not going to be as reliable as a lot of different networks could potentially have that IP.

2. You could check to see what your external public IP address is.  You could try resolving it to see if it contains "netangel" in the string (for example. `vpn1.netangel.cloud`).  Or just leave it unresolved and check the IP address.  We currently only have 1 IP, and that is `147.75.199.59`.

**Comment by eterry1388** [comment]
A third option would be to create an api that would return if the device is connected or not.  We do have this information on the rails side, but just haven't exposed it through an api.

**Comment by klinker24** [comment]
Perfect, exactly what I was hoping for! I think we can start with option 2 and see how that goes.

**Comment by eterry1388** [comment]
One thing to watch out for, many of our customers have the NetAngel Router installed in their home.  So I would assume many Android app installs would be connected to the WiFi and already protected through the home network.  I don't think I mind having this app tunnel another VPN through the VPN connected from the router in the home.  But just keep that in mind when coding this.  There is a condition where the public IP would be on the NetAngel VPN, but the VPN on the phone is not enabled or turned on.

**Comment by klinker24** [comment]
Thanks for the heads up, shouldn't be an issue!
