### ISSUE TITLE
Setup Wizard with Device Administrator

### ISSUE THREAD

**Issue by eterry1388** [net-angel/netangel-protection-android#25]
I had a thought on the current workflow of the Device Administrator setup.  What if rather than give the user the option to make it a device administrator or not, we **make** them do it.  Various ways of doing this.  Here is one idea:

1. Initial sign in into the app
2. Starts a setup wizard of some sort
3. The first step would be a screen that has information about why the need to enable the app as a device administrator, then a button to do so.
4. They click the button and enabled the device administrator
5. They are redirected back to the app and move on to the next step of the wizard
6. This is the part where they can toggle on the switch to connect
7. After it connects successfully, the last page is a message about how the device is protected and then a "sign out" button

The next time the log into the app, it would just be one screen with the toggle switch, and a button to disassociate the device with the account.  If they disassociate the device, the next time the app is logged into (presumably by a different account), they would go through the initial setup wizard again.

In the future I could see this setup wizard having a page for battery saver, for installing our custom NetAngel SSL cert for decrypting HTTPS websites, etc.

What are your thoughts?  @klinker24 How much time would this take?

**Comment by eterry1388** [comment]
@brnmckllr Your thoughts too?

**Comment by klinker24** [comment]
Sounds good to me. Wouldn't be too difficult to get it up and running, a setup screen like this is pretty common with Android apps

**Comment by klinker24** [comment]
Here is a video demonstrating the new intro pager: https://youtu.be/2S3CnKxPW8w

**Comment by klinker24** [comment]
Here is the final onboarding/setup wizard:

![screenshot_20170302-080040](https://cloud.githubusercontent.com/assets/4874287/23510445/43e0aeda-ff1f-11e6-9e97-885cd6af921d.png)
![screenshot_20170302-080044](https://cloud.githubusercontent.com/assets/4874287/23510448/4563ccba-ff1f-11e6-8ba4-2fc2916b3922.png)
![screenshot_20170302-080048](https://cloud.githubusercontent.com/assets/4874287/23510449/47627bba-ff1f-11e6-87cf-f6c4f4a16ccd.png)
![screenshot_20170302-080054](https://cloud.githubusercontent.com/assets/4874287/23510451/494f7856-ff1f-11e6-823d-35dc75452f4a.png)
