### ISSUE TITLE
Don't call API without a client_id

### ISSUE THREAD

**Issue by eterry1388** [net-angel/netangel-protection-android#32]
Looking in the API server logs, there are times when the api `/api/v1/devices//check_in` is called.  Noice how there is no client_id between "devices" and "check_in".  How did someone's app get in this state?  What can we do about it?  Maybe if there is no client_id, call the api to create a whole new device and get a new client_id (with the cert and the secret token)?  But at least avoid calling the api if there is no client_id.

**Comment by klinker24** [comment]
I would say that we should put this one on "watch" for the next update. 

The current play store version had the app starting the `CheckInService` immediately when the application was installed (from the [NetAngelApplication](https://github.com/net-angel/netangel-protection-android/blob/e49bbc92596d3e497430a94551f2cf1754b02b1f/app/src/main/java/com/netangel/netangelprotection/NetAngelApplication.java) class).

With the latest changes, it will only start that if they have already logged in, and the VPN was turned on. These changes were made in this commit: https://github.com/net-angel/netangel-protection-android/commit/b7b0e52df664ef2aa2c291be023e94786d08370a

So I don't think that this should happen anymore, but I am going to make sure the API is not called, if the client_id doesn't exist in the app.
