### ISSUE TITLE
Regularly check to see if Internet is up

### ISSUE THREAD

**Issue by eterry1388** [net-angel/netangel-protection-android#4]
To make app more reliable, have a background job that occasionally checks to see if the Internet is up.  If the internet is supposed to be up, and it is not, then restart the VPN connection automatically.

Make this intelligent so it doesn't restart the VPN service if there is not supposed to be internet (for example, if there is no mobile data available or if they are not connected to the wifi).  So if there is _supposed_ to be internet, and there is not, restart the VPN service.

Couple ways to check to see if Internet is up.  Research to see what is best.  Possibilities include doing a simple ping to a server, doing a wget/curl type check to see if can get HTTP response from a server, or doing a DNS request to see if can get a domain to resolve.  On our routers, we have a background job that does this:

```sh
check_if_internet_up() {
  curl --connect-timeout 3 --max-time 3 --retry 3 http://netangel.com
}
```

On the routers, we check to see if it is on the VPN before checking to see if the internet is up.  If it is not on the VPN, it restarts the VPN.  If it is on the VPN, it checks to see if internet is up.  If it is not up, it restarts the VPN.  Maybe a similar process would make sense for this Android app.  This is the check we do on the router to see if on VPN:

```sh
check_if_on_vpn() {
  ping -c 3 -W 3 172.18.0.1
}
```

Maybe start out with this job running every 5 minutes.

**Comment by klinker24** [comment]
The way I usually do this on Android would be something like:

```java
private boolean hasConnection() {
    HttpURLConnection urlc = (HttpURLConnection) (new URL("http://clients3.google.com/generate_204").openConnection());
    urlc.setConnectTimeout(2000); 
    urlc.connect();

    return (urlc.getResponseCode() == 204 && urlc.getContentLength() == 0);
}
```

This is actually the way that Android does it internally, I believe. The `http://clients3.google.com/generate_204` is a really quick url to hit.
