### ISSUE TITLE
Public issue in GitHub compromises App security

### ISSUE THREAD

**Issue by palmercluff** [net-angel/netangel-protection-android#42]
When googling "how to uninstall netangel app", one of our issues comes up with clear directions how to disable the app! Issue #10 should probably be opened back up because my wife read through the instructions on how to uninstall it, and it still works (She has been helping me test it). If I was a teenager, this is one of the first things I would do. "How to uninstall NetAngel"

@eterry1388 Maybe we should consider making this a private repository so that this issue does not show up!

**Comment by eterry1388** [comment]
@palmercluff Issue #10 shows how to disable as device administrator to uninstall the app.  But doing so should have sent a text message out.  Did you get a text message?  There is no way to really prevent the uninstallation of an app on Android.  But the point was, we wanted to make it more difficult.  And if they DID disable it as a device administrator, we wanted a text message alert to be sent out.  If a text was sent out, we can close this issue.

**Comment by palmercluff** [comment]
The text is sent out. That works perfectly. I wasn't sure if there was a way to prevent the installation of an app on Android, so I thought I would bring it up. Sorry I should have read the entire issue.
