### ISSUE TITLE
Can't enable as device administrator on main screen

### ISSUE THREAD

**Issue by eterry1388** [net-angel/netangel-protection-android#46]
I went through the initial setup wizard, enabling as a device administrator.  I then clicked the "Allow Uninstall" button on the main screen.  Then clicking "Prevent Uninstall" pops up a message about enabling as a device administrator.  When I click "Enable", the app closes and does NOT enable as a device administrator.

**Comment by klinker24** [comment]
I made some changes with #47, and an explanation of what was happening
