### ISSUE TITLE
Save state of toggle button permanently

### ISSUE THREAD

**Issue by eterry1388** [net-angel/netangel-protection-android#5]
The app doesn't seem to always remember it is supposed to be connected to the VPN.  We need to change this so that if the toggle button is flipped on to protect the device, it will **always** remember that setting.  The **only** time that state should change to off is when the user toggles that to off.

So even if the device is rebooted, or the VPN connection dies, or the user manually "forgets" the VPN connection in the Android settings, etc., the NetAngel app will remember what state it is _supposed_ to be in.

The app can use this permanent state to know if it is supposed to automatically flip the VPN back on when it is off (manually forgotten in Android settings by user, restarted device, VPN connection died, etc.).

**Comment by klinker24** [comment]
This one should be finished, after #15, #14, and #8. I don't think that I am missing any cases. 

This will get:
- device restarts
- user "forgets" the VPN
- VPN connection dies when switching networks
- the app is updated
- whenever the app is started (if it were to crash on a user for whatever reason... I haven't seen any crashes while testing)

**Comment by eterry1388** [comment]
I can't get it to forget the state of the setting.  Closing issue.
